/**
 * This file was generated by
 * bin2cpp v1.3.
 * Copyright (C) 2013-2014 end2endzone.com. All rights reserved.
 * Do not modify this file.
 */
#include ".\EmbeddedFileServerProject.h"
#include <stdio.h> //for FILE
#include <string> //for memcpy
namespace bin2cpp
{
  class ServerProjectFile : public virtual bin2cpp::File
  {
  public:
    ServerProjectFile() {}
    ~ServerProjectFile() {}
    virtual size_t getSize() { return 8174; }
    virtual size_t getSegmentSize() { return 200; }
    virtual size_t getNumSegments() { return 41; }
    virtual const char * getFilename() { return "DCOMPLUGIN_COMPONENT_NAMEServer.vcxproj"; }
    virtual const char * getSegment(size_t iIndex, size_t & oLength)
    {
      oLength = 0;
      if (iIndex >= getNumSegments())
        return NULL;
      const char * buffer = NULL;
      size_t index = 0;
      oLength = getSegmentSize();
      buffer = "\xef\xbb\277<?xml version=\"1.0\" encoding=\"utf-8\"?>\x0d\012<Project DefaultTargets=\"Build\" ToolsVersion=\"4.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\x0d\012  <ItemGroup Label=\"ProjectConfigurations\">\x0d"; if (iIndex == index) return buffer; index++;
      buffer = "\012    <ProjectConfiguration Include=\"Debug|Win32\">\x0d\012      <Configuration>Debug</Configuration>\x0d\012      <Platform>Win32</Platform>\x0d\012    </ProjectConfiguration>\x0d\012    <ProjectConfiguration Include=\"Release"; if (iIndex == index) return buffer; index++;
      buffer = "|Win32\">\x0d\012      <Configuration>Release</Configuration>\x0d\012      <Platform>Win32</Platform>\x0d\012    </ProjectConfiguration>\x0d\012  </ItemGroup>\x0d\012  <PropertyGroup Label=\"Globals\">\x0d\012    <ProjectName>DCOMPLUGIN_CO"; if (iIndex == index) return buffer; index++;
      buffer = "MPONENT_NAMEServer</ProjectName>\x0d\012    <ProjectGuid>{DCOMPLUGIN_SERVER_PROJECT_GUID_UPPER}</ProjectGuid>\x0d\012    <RootNamespace>DCOMPLUGIN_COMPONENT_NAMEServer</RootNamespace>\x0d\012  </PropertyGroup>\x0d\012  <Impo"; if (iIndex == index) return buffer; index++;
      buffer = "rt Project=\"$(VCTargetsPath)\\Microsoft.Cpp.Default.props\" />\x0d\012  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\" Label=\"Configuration\">\x0d\012    <ConfigurationType>Application</C"; if (iIndex == index) return buffer; index++;
      buffer = "onfigurationType>\x0d\012    <UseOfMfc>false</UseOfMfc>\x0d\012    <CharacterSet>MultiByte</CharacterSet>\x0d\012  </PropertyGroup>\x0d\012  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\" Label=\"Con"; if (iIndex == index) return buffer; index++;
      buffer = "figuration\">\x0d\012    <ConfigurationType>Application</ConfigurationType>\x0d\012    <UseOfMfc>false</UseOfMfc>\x0d\012    <CharacterSet>MultiByte</CharacterSet>\x0d\012  </PropertyGroup>\x0d\012  <Import Project=\"$(VCTargetsPath"; if (iIndex == index) return buffer; index++;
      buffer = ")\\Microsoft.Cpp.props\" />\x0d\012  <ImportGroup Label=\"ExtensionSettings\">\x0d\012  </ImportGroup>\x0d\012  <ImportGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\" Label=\"PropertySheets\">\x0d\012    <Import "; if (iIndex == index) return buffer; index++;
      buffer = "Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\x0d\012    <Import Project=\"$(VCTarget"; if (iIndex == index) return buffer; index++;
      buffer = "sPath)Microsoft.CPP.UpgradeFromVC71.props\" />\x0d\012  </ImportGroup>\x0d\012  <ImportGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\" Label=\"PropertySheets\">\x0d\012    <Import Project=\"$(UserRootDir)\\M"; if (iIndex == index) return buffer; index++;
      buffer = "icrosoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\x0d\012    <Import Project=\"$(VCTargetsPath)Microsoft.CPP.Upgra"; if (iIndex == index) return buffer; index++;
      buffer = "deFromVC71.props\" />\x0d\012  </ImportGroup>\x0d\012  <PropertyGroup Label=\"UserMacros\" />\x0d\012  <PropertyGroup>\x0d\012    <_ProjectFileVersion>10.0.40219.1</_ProjectFileVersion>\x0d\012    <OutDir Condition=\"'$(Configuration)"; if (iIndex == index) return buffer; index++;
      buffer = "|$(Platform)'=='Debug|Win32'\">$(SolutionDir)$(Configuration)\\</OutDir>\x0d\012    <IntDir Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">$(Configuration)\\</IntDir>\x0d\012    <LinkIncremental Condition"; if (iIndex == index) return buffer; index++;
      buffer = "=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">true</LinkIncremental>\x0d\012    <OutDir Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">$(SolutionDir)$(Configuration)\\</OutDir>\x0d\012    <IntDir C"; if (iIndex == index) return buffer; index++;
      buffer = "ondition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">$(Configuration)\\</IntDir>\x0d\012    <LinkIncremental Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">false</LinkIncremental>\x0d\012  </Pro"; if (iIndex == index) return buffer; index++;
      buffer = "pertyGroup>\x0d\012  <ItemDefinitionGroup Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">\x0d\012    <Midl>\x0d\012      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>\x0d\x0a"; if (iIndex == index) return buffer; index++;
      buffer = "      <MkTypLibCompatible>false</MkTypLibCompatible>\x0d\012      <TargetEnvironment>Win32</TargetEnvironment>\x0d\012      <TypeLibraryName>.\\$(Configuration)/$(ProjectName).tlb</TypeLibraryName>\x0d\012      <Generat"; if (iIndex == index) return buffer; index++;
      buffer = "eStublessProxies>true</GenerateStublessProxies>\x0d\012    </Midl>\x0d\012    <ClCompile>\x0d\012      <Optimization>Disabled</Optimization>\x0d\012      <PreprocessorDefinitions>WIN32;_DEBUG;_WINDOWS;_CRT_SECURE_NO_WARNINGS"; if (iIndex == index) return buffer; index++;
      buffer = ";_SCL_SECURE_NO_WARNINGS;_SCL_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>\x0d\012      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>\x0d\012      <RuntimeLibrary>MultiThrea"; if (iIndex == index) return buffer; index++;
      buffer = "dedDebugDLL</RuntimeLibrary>\x0d\012      <PrecompiledHeader>NotUsing</PrecompiledHeader>\x0d\012      <PrecompiledHeaderFile>\x0d\012      </PrecompiledHeaderFile>\x0d\012      <PrecompiledHeaderOutputFile>\x0d\012      </Precomp"; if (iIndex == index) return buffer; index++;
      buffer = "iledHeaderOutputFile>\x0d\012      <WarningLevel>Level3</WarningLevel>\x0d\012      <SuppressStartupBanner>true</SuppressStartupBanner>\x0d\012      <DebugInformationFormat>EditAndContinue</DebugInformationFormat>\x0d\012   "; if (iIndex == index) return buffer; index++;
      buffer = "   <AdditionalIncludeDirectories>$(PROTOBUF_INCLUDE_DIR)</AdditionalIncludeDirectories>\x0d\012    </ClCompile>\x0d\012    <ResourceCompile>\x0d\012      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</Prep"; if (iIndex == index) return buffer; index++;
      buffer = "rocessorDefinitions>\x0d\012      <Culture>0x0409</Culture>\x0d\012    </ResourceCompile>\x0d\012    <Link>\x0d\012      <AdditionalOptions>/MACHINE:I386 %(AdditionalOptions)</AdditionalOptions>\x0d\012      <AdditionalDependencie"; if (iIndex == index) return buffer; index++;
      buffer = "s>$(PROTOBUF_DEBUG_LIBRARIES);%(AdditionalDependencies)</AdditionalDependencies>\x0d\012      <OutputFile>$(OutDir)$(ProjectName).exe</OutputFile>\x0d\012      <SuppressStartupBanner>true</SuppressStartupBanner>\x0d"; if (iIndex == index) return buffer; index++;
      buffer = "\012      <GenerateDebugInformation>true</GenerateDebugInformation>\x0d\012      <SubSystem>Windows</SubSystem>\x0d\012      <RandomizedBaseAddress>false</RandomizedBaseAddress>\x0d\012      <DataExecutionPrevention>\x0d\012   "; if (iIndex == index) return buffer; index++;
      buffer = "   </DataExecutionPrevention>\x0d\012      <AdditionalLibraryDirectories>$(PROTOBUF_LIB_DIR)\\$(ConfigurationName)</AdditionalLibraryDirectories>\x0d\012    </Link>\x0d\012  </ItemDefinitionGroup>\x0d\012  <ItemDefinitionGrou"; if (iIndex == index) return buffer; index++;
      buffer = "p Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">\x0d\012    <Midl>\x0d\012      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>\x0d\012      <MkTypLibCompatible>false<"; if (iIndex == index) return buffer; index++;
      buffer = "/MkTypLibCompatible>\x0d\012      <TargetEnvironment>Win32</TargetEnvironment>\x0d\012      <TypeLibraryName>.\\$(Configuration)/$(ProjectName).tlb</TypeLibraryName>\x0d\012      <GenerateStublessProxies>true</GenerateS"; if (iIndex == index) return buffer; index++;
      buffer = "tublessProxies>\x0d\012    </Midl>\x0d\012    <ClCompile>\x0d\012      <InlineFunctionExpansion>OnlyExplicitInline</InlineFunctionExpansion>\x0d\012      <PreprocessorDefinitions>WIN32;NDEBUG;_WINDOWS;_CRT_SECURE_NO_WARNINGS"; if (iIndex == index) return buffer; index++;
      buffer = ";_SCL_SECURE_NO_WARNINGS;_SCL_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>\x0d\012      <StringPooling>true</StringPooling>\x0d\012      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary"; if (iIndex == index) return buffer; index++;
      buffer = ">\x0d\012      <FunctionLevelLinking>true</FunctionLevelLinking>\x0d\012      <PrecompiledHeader>NotUsing</PrecompiledHeader>\x0d\012      <PrecompiledHeaderFile>\x0d\012      </PrecompiledHeaderFile>\x0d\012      <PrecompiledHead"; if (iIndex == index) return buffer; index++;
      buffer = "erOutputFile>\x0d\012      </PrecompiledHeaderOutputFile>\x0d\012      <WarningLevel>Level3</WarningLevel>\x0d\012      <SuppressStartupBanner>true</SuppressStartupBanner>\x0d\012      <AdditionalIncludeDirectories>$(PROTOBU"; if (iIndex == index) return buffer; index++;
      buffer = "F_INCLUDE_DIR)</AdditionalIncludeDirectories>\x0d\012    </ClCompile>\x0d\012    <ResourceCompile>\x0d\012      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>\x0d\012      <Culture>0x040"; if (iIndex == index) return buffer; index++;
      buffer = "9</Culture>\x0d\012    </ResourceCompile>\x0d\012    <Link>\x0d\012      <AdditionalOptions>/MACHINE:I386 %(AdditionalOptions)</AdditionalOptions>\x0d\012      <AdditionalDependencies>$(PROTOBUF_RELEASE_LIBRARIES);%(Addition"; if (iIndex == index) return buffer; index++;
      buffer = "alDependencies)</AdditionalDependencies>\x0d\012      <OutputFile>$(OutDir)$(ProjectName).exe</OutputFile>\x0d\012      <SuppressStartupBanner>true</SuppressStartupBanner>\x0d\012      <SubSystem>Windows</SubSystem>\x0d\012 "; if (iIndex == index) return buffer; index++;
      buffer = "     <RandomizedBaseAddress>false</RandomizedBaseAddress>\x0d\012      <DataExecutionPrevention>\x0d\012      </DataExecutionPrevention>\x0d\012      <AdditionalLibraryDirectories>$(PROTOBUF_LIB_DIR)\\$(ConfigurationNam"; if (iIndex == index) return buffer; index++;
      buffer = "e)</AdditionalLibraryDirectories>\x0d\012    </Link>\x0d\012  </ItemDefinitionGroup>\x0d\012  <ItemGroup>\x0d\012    <ClCompile Include=\"DCOMPLUGIN_COMPONENT_NAMEServer.cpp\" />\x0d\012    <ClCompile Include=\"DCOMPLUGIN_COMPONENT_N"; if (iIndex == index) return buffer; index++;
      buffer = "AMEServerMain.cpp\" />\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <Midl Include=\"DCOMPLUGIN_COMPONENT_NAMEServer.idl\" />\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <ClInclude Include=\"DCOMPLUGIN_COMPONENT_NAMEServer"; if (iIndex == index) return buffer; index++;
      buffer = ".h\" />\x0d\012    <ClInclude Include=\"SmartPointers.h\" />\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <ProjectReference Include=\"DCOMPLUGIN_COMPONENT_NAMEProtoLib.vcxproj\">\x0d\012      <Project>{DCOMPLUGIN_PROTOLIB_PROJ"; if (iIndex == index) return buffer; index++;
      buffer = "ECT_GUID_LOWER}</Project>\x0d\012    </ProjectReference>\x0d\012    <ProjectReference Include=\"DCOMPLUGIN_COMPONENT_NAMEServerImpl.vcxproj\">\x0d\012      <Project>{DCOMPLUGIN_SERVER_IMPL_PROJECT_GUID_LOWER}</Project>\x0d\x0a"; if (iIndex == index) return buffer; index++;
      oLength = 174;
      buffer = "    </ProjectReference>\x0d\012  </ItemGroup>\x0d\012  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.targets\" />\x0d\012  <ImportGroup Label=\"ExtensionTargets\">\x0d\012  </ImportGroup>\x0d\012</Project>"; if (iIndex == index) return buffer; index++;
      oLength = 0;
      return NULL;
    }
    virtual const char * getMd5() { return "ed58492827b4f9e0eb4d65857e9d7f51"; }
    virtual char * newBuffer()
    {
      size_t size = getSize();
      char * buffer = new char[size];
      if (buffer == NULL)
        return NULL;
      size_t numSegments = getNumSegments();
      size_t segmentLength = 0;
      size_t index = 0;
      for(size_t i=0; i<numSegments; i++)
      {
        const char * segmentBuffer = getSegment(i, segmentLength);
        memcpy(&buffer[index], segmentBuffer, segmentLength);
        index += segmentLength;
      }
      return buffer;
    }
    virtual bool save(const char * iFilename)
    {
      FILE * f = fopen(iFilename, "wb");
      if (!f) return false;
      size_t numSegments = getNumSegments();
      size_t segmentLength = 0;
      const char * buffer = NULL;
      for(size_t i=0; i<numSegments; i++)
      {
        buffer = getSegment(i, segmentLength);
        fwrite(buffer, 1, segmentLength, f);
      }
      fclose(f);
      return true;
    }
  };
  File & getServerProjectFile() { static ServerProjectFile _instance; return _instance; }
}; //bin2cpp
