/**
 * This file was generated by bin2cpp v2.2.0
 * Copyright (C) 2013-2019 end2endzone.com. All rights reserved.
 * bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp
 * Source code for file 'DCOMPLUGIN_COMPONENT_NAMEServer.vcxproj', last modified 1552228002.
 * Do not modify this file.
 */
#include "EmbeddedFileServerProject.h"
#include <stdio.h> //for FILE
#include <string> //for memcpy
namespace bin2cpp
{
  class ServerProjectFile : public virtual bin2cpp::File
  {
  public:
    ServerProjectFile() { build(); }
    virtual ~ServerProjectFile() {}
    virtual size_t getSize() const { return 8174; }
    virtual const char * getFilename() const { return "DCOMPLUGIN_COMPONENT_NAMEServer.vcxproj"; }
    virtual const char * getBuffer() const { return mBuffer.c_str(); }
    void build()
    {
      mBuffer.clear();
      mBuffer.reserve(getSize()); //allocate all required memory at once to prevent reallocations
      mBuffer.append("\357\273\277<\?xml version=\"1.0\" encoding=\"utf-8\"\?>\r\n<Project DefaultTargets=\"Build\" ToolsVersion=\"4.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\r\n  <ItemGroup Label=\"ProjectConfigurations\">\r", 200);
      mBuffer.append("\n    <ProjectConfiguration Include=\"Debug|Win32\">\r\n      <Configuration>Debug</Configuration>\r\n      <Platform>Win32</Platform>\r\n    </ProjectConfiguration>\r\n    <ProjectConfiguration Include=\"Release", 200);
      mBuffer.append("|Win32\">\r\n      <Configuration>Release</Configuration>\r\n      <Platform>Win32</Platform>\r\n    </ProjectConfiguration>\r\n  </ItemGroup>\r\n  <PropertyGroup Label=\"Globals\">\r\n    <ProjectName>DCOMPLUGIN_CO", 200);
      mBuffer.append("MPONENT_NAMEServer</ProjectName>\r\n    <ProjectGuid>{DCOMPLUGIN_SERVER_PROJECT_GUID_UPPER}</ProjectGuid>\r\n    <RootNamespace>DCOMPLUGIN_COMPONENT_NAMEServer</RootNamespace>\r\n  </PropertyGroup>\r\n  <Impo", 200);
      mBuffer.append("rt Project=\"$(VCTargetsPath)\\Microsoft.Cpp.Default.props\" />\r\n  <PropertyGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Release|Win32\'\" Label=\"Configuration\">\r\n    <ConfigurationType>Application</C", 200);
      mBuffer.append("onfigurationType>\r\n    <UseOfMfc>false</UseOfMfc>\r\n    <CharacterSet>MultiByte</CharacterSet>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Debug|Win32\'\" Label=\"Con", 200);
      mBuffer.append("figuration\">\r\n    <ConfigurationType>Application</ConfigurationType>\r\n    <UseOfMfc>false</UseOfMfc>\r\n    <CharacterSet>MultiByte</CharacterSet>\r\n  </PropertyGroup>\r\n  <Import Project=\"$(VCTargetsPath", 200);
      mBuffer.append(")\\Microsoft.Cpp.props\" />\r\n  <ImportGroup Label=\"ExtensionSettings\">\r\n  </ImportGroup>\r\n  <ImportGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Release|Win32\'\" Label=\"PropertySheets\">\r\n    <Import ", 200);
      mBuffer.append("Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists(\'$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\')\" Label=\"LocalAppDataPlatform\" />\r\n    <Import Project=\"$(VCTarget", 200);
      mBuffer.append("sPath)Microsoft.CPP.UpgradeFromVC71.props\" />\r\n  </ImportGroup>\r\n  <ImportGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Debug|Win32\'\" Label=\"PropertySheets\">\r\n    <Import Project=\"$(UserRootDir)\\M", 200);
      mBuffer.append("icrosoft.Cpp.$(Platform).user.props\" Condition=\"exists(\'$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\')\" Label=\"LocalAppDataPlatform\" />\r\n    <Import Project=\"$(VCTargetsPath)Microsoft.CPP.Upgra", 200);
      mBuffer.append("deFromVC71.props\" />\r\n  </ImportGroup>\r\n  <PropertyGroup Label=\"UserMacros\" />\r\n  <PropertyGroup>\r\n    <_ProjectFileVersion>10.0.40219.1</_ProjectFileVersion>\r\n    <OutDir Condition=\"\'$(Configuration)", 200);
      mBuffer.append("|$(Platform)\'==\'Debug|Win32\'\">$(SolutionDir)$(Configuration)\\</OutDir>\r\n    <IntDir Condition=\"\'$(Configuration)|$(Platform)\'==\'Debug|Win32\'\">$(Configuration)\\</IntDir>\r\n    <LinkIncremental Condition", 200);
      mBuffer.append("=\"\'$(Configuration)|$(Platform)\'==\'Debug|Win32\'\">true</LinkIncremental>\r\n    <OutDir Condition=\"\'$(Configuration)|$(Platform)\'==\'Release|Win32\'\">$(SolutionDir)$(Configuration)\\</OutDir>\r\n    <IntDir C", 200);
      mBuffer.append("ondition=\"\'$(Configuration)|$(Platform)\'==\'Release|Win32\'\">$(Configuration)\\</IntDir>\r\n    <LinkIncremental Condition=\"\'$(Configuration)|$(Platform)\'==\'Release|Win32\'\">false</LinkIncremental>\r\n  </Pro", 200);
      mBuffer.append("pertyGroup>\r\n  <ItemDefinitionGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Debug|Win32\'\">\r\n    <Midl>\r\n      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n", 200);
      mBuffer.append("      <MkTypLibCompatible>false</MkTypLibCompatible>\r\n      <TargetEnvironment>Win32</TargetEnvironment>\r\n      <TypeLibraryName>.\\$(Configuration)/$(ProjectName).tlb</TypeLibraryName>\r\n      <Generat", 200);
      mBuffer.append("eStublessProxies>true</GenerateStublessProxies>\r\n    </Midl>\r\n    <ClCompile>\r\n      <Optimization>Disabled</Optimization>\r\n      <PreprocessorDefinitions>WIN32;_DEBUG;_WINDOWS;_CRT_SECURE_NO_WARNINGS", 200);
      mBuffer.append(";_SCL_SECURE_NO_WARNINGS;_SCL_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n      <BasicRuntimeChecks>EnableFastChecks</BasicRuntimeChecks>\r\n      <RuntimeLibrary>MultiThrea", 200);
      mBuffer.append("dedDebugDLL</RuntimeLibrary>\r\n      <PrecompiledHeader>NotUsing</PrecompiledHeader>\r\n      <PrecompiledHeaderFile>\r\n      </PrecompiledHeaderFile>\r\n      <PrecompiledHeaderOutputFile>\r\n      </Precomp", 200);
      mBuffer.append("iledHeaderOutputFile>\r\n      <WarningLevel>Level3</WarningLevel>\r\n      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n      <DebugInformationFormat>EditAndContinue</DebugInformationFormat>\r\n   ", 200);
      mBuffer.append("   <AdditionalIncludeDirectories>$(PROTOBUF_INCLUDE_DIR)</AdditionalIncludeDirectories>\r\n    </ClCompile>\r\n    <ResourceCompile>\r\n      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</Prep", 200);
      mBuffer.append("rocessorDefinitions>\r\n      <Culture>0x0409</Culture>\r\n    </ResourceCompile>\r\n    <Link>\r\n      <AdditionalOptions>/MACHINE:I386 %(AdditionalOptions)</AdditionalOptions>\r\n      <AdditionalDependencie", 200);
      mBuffer.append("s>$(PROTOBUF_DEBUG_LIBRARIES);%(AdditionalDependencies)</AdditionalDependencies>\r\n      <OutputFile>$(OutDir)$(ProjectName).exe</OutputFile>\r\n      <SuppressStartupBanner>true</SuppressStartupBanner>\r", 200);
      mBuffer.append("\n      <GenerateDebugInformation>true</GenerateDebugInformation>\r\n      <SubSystem>Windows</SubSystem>\r\n      <RandomizedBaseAddress>false</RandomizedBaseAddress>\r\n      <DataExecutionPrevention>\r\n   ", 200);
      mBuffer.append("   </DataExecutionPrevention>\r\n      <AdditionalLibraryDirectories>$(PROTOBUF_LIB_DIR)\\$(ConfigurationName)</AdditionalLibraryDirectories>\r\n    </Link>\r\n  </ItemDefinitionGroup>\r\n  <ItemDefinitionGrou", 200);
      mBuffer.append("p Condition=\"\'$(Configuration)|$(Platform)\'==\'Release|Win32\'\">\r\n    <Midl>\r\n      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n      <MkTypLibCompatible>false<", 200);
      mBuffer.append("/MkTypLibCompatible>\r\n      <TargetEnvironment>Win32</TargetEnvironment>\r\n      <TypeLibraryName>.\\$(Configuration)/$(ProjectName).tlb</TypeLibraryName>\r\n      <GenerateStublessProxies>true</GenerateS", 200);
      mBuffer.append("tublessProxies>\r\n    </Midl>\r\n    <ClCompile>\r\n      <InlineFunctionExpansion>OnlyExplicitInline</InlineFunctionExpansion>\r\n      <PreprocessorDefinitions>WIN32;NDEBUG;_WINDOWS;_CRT_SECURE_NO_WARNINGS", 200);
      mBuffer.append(";_SCL_SECURE_NO_WARNINGS;_SCL_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n      <StringPooling>true</StringPooling>\r\n      <RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary", 200);
      mBuffer.append(">\r\n      <FunctionLevelLinking>true</FunctionLevelLinking>\r\n      <PrecompiledHeader>NotUsing</PrecompiledHeader>\r\n      <PrecompiledHeaderFile>\r\n      </PrecompiledHeaderFile>\r\n      <PrecompiledHead", 200);
      mBuffer.append("erOutputFile>\r\n      </PrecompiledHeaderOutputFile>\r\n      <WarningLevel>Level3</WarningLevel>\r\n      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n      <AdditionalIncludeDirectories>$(PROTOBU", 200);
      mBuffer.append("F_INCLUDE_DIR)</AdditionalIncludeDirectories>\r\n    </ClCompile>\r\n    <ResourceCompile>\r\n      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n      <Culture>0x040", 200);
      mBuffer.append("9</Culture>\r\n    </ResourceCompile>\r\n    <Link>\r\n      <AdditionalOptions>/MACHINE:I386 %(AdditionalOptions)</AdditionalOptions>\r\n      <AdditionalDependencies>$(PROTOBUF_RELEASE_LIBRARIES);%(Addition", 200);
      mBuffer.append("alDependencies)</AdditionalDependencies>\r\n      <OutputFile>$(OutDir)$(ProjectName).exe</OutputFile>\r\n      <SuppressStartupBanner>true</SuppressStartupBanner>\r\n      <SubSystem>Windows</SubSystem>\r\n ", 200);
      mBuffer.append("     <RandomizedBaseAddress>false</RandomizedBaseAddress>\r\n      <DataExecutionPrevention>\r\n      </DataExecutionPrevention>\r\n      <AdditionalLibraryDirectories>$(PROTOBUF_LIB_DIR)\\$(ConfigurationNam", 200);
      mBuffer.append("e)</AdditionalLibraryDirectories>\r\n    </Link>\r\n  </ItemDefinitionGroup>\r\n  <ItemGroup>\r\n    <ClCompile Include=\"DCOMPLUGIN_COMPONENT_NAMEServer.cpp\" />\r\n    <ClCompile Include=\"DCOMPLUGIN_COMPONENT_N", 200);
      mBuffer.append("AMEServerMain.cpp\" />\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <Midl Include=\"DCOMPLUGIN_COMPONENT_NAMEServer.idl\" />\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <ClInclude Include=\"DCOMPLUGIN_COMPONENT_NAMEServer", 200);
      mBuffer.append(".h\" />\r\n    <ClInclude Include=\"SmartPointers.h\" />\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <ProjectReference Include=\"DCOMPLUGIN_COMPONENT_NAMEProtoLib.vcxproj\">\r\n      <Project>{DCOMPLUGIN_PROTOLIB_PROJ", 200);
      mBuffer.append("ECT_GUID_LOWER}</Project>\r\n    </ProjectReference>\r\n    <ProjectReference Include=\"DCOMPLUGIN_COMPONENT_NAMEServerImpl.vcxproj\">\r\n      <Project>{DCOMPLUGIN_SERVER_IMPL_PROJECT_GUID_LOWER}</Project>\r\n", 200);
      mBuffer.append("    </ProjectReference>\r\n  </ItemGroup>\r\n  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.targets\" />\r\n  <ImportGroup Label=\"ExtensionTargets\">\r\n  </ImportGroup>\r\n</Project>", 174);
    }
    virtual bool save(const char * iFilename) const
    {
      FILE * f = fopen(iFilename, "wb");
      if (!f) return false;
      size_t fileSize = getSize();
      const char * buffer = getBuffer();
      fwrite(buffer, 1, fileSize, f);
      fclose(f);
      return true;
    }
  private:
    std::string mBuffer;
  };
  const File & getServerProjectFile() { static ServerProjectFile _instance; return _instance; }
}; //bin2cpp
