/**
 * This file was generated by bin2cpp v2.2.0
 * Copyright (C) 2013-2019 end2endzone.com. All rights reserved.
 * bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp
 * Source code for file 'IService.h', last modified 1552228002.
 * Do not modify this file.
 */
#include "EmbeddedFileIService.h"
#include <stdio.h> //for FILE
#include <string> //for memcpy
namespace bin2cpp
{
  class IServiceFile : public virtual bin2cpp::File
  {
  public:
    IServiceFile() { build(); }
    virtual ~IServiceFile() {}
    virtual size_t getSize() const { return 194; }
    virtual const char * getFilename() const { return "IService.h"; }
    virtual const char * getBuffer() const { return mBuffer.c_str(); }
    void build()
    {
      mBuffer.clear();
      mBuffer.reserve(getSize()); //allocate all required memory at once to prevent reallocations
      mBuffer.append("#pragma once\r\n\r\n#include \"DCOMPLUGIN_PROTO_FILE_NAME.pb.h\"\r\n\r\nnamespace DCOMPLUGIN_PACKAGE_NAME {\r\n\r\nDCOMPLUGIN_CURRENT_SERVICE_INTERFACE_DECLARATION\r\n\r\n}  // namespace DCOMPLUGIN_PACKAGE_NAME\r\n", 194);
    }
    virtual bool save(const char * iFilename) const
    {
      FILE * f = fopen(iFilename, "wb");
      if (!f) return false;
      size_t fileSize = getSize();
      const char * buffer = getBuffer();
      fwrite(buffer, 1, fileSize, f);
      fclose(f);
      return true;
    }
  private:
    std::string mBuffer;
  };
  const File & getIServiceFile() { static IServiceFile _instance; return _instance; }
}; //bin2cpp
