/**
 * This file was generated by
 * bin2cpp v1.3.
 * Copyright (C) 2013-2014 end2endzone.com. All rights reserved.
 * Do not modify this file.
 */
#include ".\EmbeddedFileProtoLibProject.h"
#include <stdio.h> //for FILE
#include <string> //for memcpy
namespace bin2cpp
{
  class ProtoLibProjectFile : public virtual bin2cpp::File
  {
  public:
    ProtoLibProjectFile() {}
    ~ProtoLibProjectFile() {}
    virtual size_t getSize() { return 5328; }
    virtual size_t getSegmentSize() { return 200; }
    virtual size_t getNumSegments() { return 27; }
    virtual const char * getFilename() { return "DCOMPLUGIN_COMPONENT_NAMEProtoLib.vcxproj"; }
    virtual const char * getSegment(size_t iIndex, size_t & oLength)
    {
      oLength = 0;
      if (iIndex >= getNumSegments())
        return NULL;
      const char * buffer = NULL;
      size_t index = 0;
      oLength = getSegmentSize();
      buffer = "\xef\xbb\277<?xml version=\"1.0\" encoding=\"utf-8\"?>\x0d\012<Project DefaultTargets=\"Build\" ToolsVersion=\"4.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\x0d\012  <ItemGroup Label=\"ProjectConfigurations\">\x0d"; if (iIndex == index) return buffer; index++;
      buffer = "\012    <ProjectConfiguration Include=\"Debug|Win32\">\x0d\012      <Configuration>Debug</Configuration>\x0d\012      <Platform>Win32</Platform>\x0d\012    </ProjectConfiguration>\x0d\012    <ProjectConfiguration Include=\"Release"; if (iIndex == index) return buffer; index++;
      buffer = "|Win32\">\x0d\012      <Configuration>Release</Configuration>\x0d\012      <Platform>Win32</Platform>\x0d\012    </ProjectConfiguration>\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <None Include=\"DCOMPLUGIN_PROTO_FILE_NAME.prot"; if (iIndex == index) return buffer; index++;
      buffer = "o\" />\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <ClCompile Include=\"dcomplugin.pb.cc\" />\x0d\012    <ClCompile Include=\"ErrorHandlers.cpp\" />\x0d\012    <ClCompile Include=\"MessageSerializer.cpp\" />\x0d\012    <ClCompile Inc"; if (iIndex == index) return buffer; index++;
      buffer = "lude=\"Registry.cpp\" />\x0d\012    <ClCompile Include=\"DCOMPLUGIN_PROTO_FILE_NAME.pb.cc\" />\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <ClInclude Include=\"dcomplugin.pb.h\" />\x0d\012    <ClInclude Include=\"IComErrorProvi"; if (iIndex == index) return buffer; index++;
      buffer = "der.h\" />\x0d\012    <DCOMPLUGIN_ALL_SERVICES_VCXPROJ />\x0d\012    <ClInclude Include=\"ErrorHandlers.h\" />\x0d\012    <ClInclude Include=\"MessageSerializer.h\" />\x0d\012    <ClInclude Include=\"Registry.h\" />\x0d\012    <ClInclude"; if (iIndex == index) return buffer; index++;
      buffer = " Include=\"DCOMPLUGIN_PROTO_FILE_NAME.pb.h\" />\x0d\012  </ItemGroup>\x0d\012  <PropertyGroup Label=\"Globals\">\x0d\012    <ProjectGuid>{DCOMPLUGIN_PROTOLIB_PROJECT_GUID_UPPER}</ProjectGuid>\x0d\012    <Keyword>Win32Proj</Keywo"; if (iIndex == index) return buffer; index++;
      buffer = "rd>\x0d\012    <RootNamespace>DCOMPLUGIN_COMPONENT_NAMEProtoLib</RootNamespace>\x0d\012  </PropertyGroup>\x0d\012  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.Default.props\" />\x0d\012  <PropertyGroup Condition=\"'$(Confi"; if (iIndex == index) return buffer; index++;
      buffer = "guration)|$(Platform)'=='Debug|Win32'\" Label=\"Configuration\">\x0d\012    <ConfigurationType>StaticLibrary</ConfigurationType>\x0d\012    <UseDebugLibraries>true</UseDebugLibraries>\x0d\012    <CharacterSet>MultiByte</C"; if (iIndex == index) return buffer; index++;
      buffer = "haracterSet>\x0d\012  </PropertyGroup>\x0d\012  <PropertyGroup Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\" Label=\"Configuration\">\x0d\012    <ConfigurationType>StaticLibrary</ConfigurationType>\x0d\012    <Us"; if (iIndex == index) return buffer; index++;
      buffer = "eDebugLibraries>false</UseDebugLibraries>\x0d\012    <WholeProgramOptimization>true</WholeProgramOptimization>\x0d\012    <CharacterSet>MultiByte</CharacterSet>\x0d\012  </PropertyGroup>\x0d\012  <Import Project=\"$(VCTargets"; if (iIndex == index) return buffer; index++;
      buffer = "Path)\\Microsoft.Cpp.props\" />\x0d\012  <ImportGroup Label=\"ExtensionSettings\">\x0d\012  </ImportGroup>\x0d\012  <ImportGroup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Debug|Win32'\">\x0d\012    <Impor"; if (iIndex == index) return buffer; index++;
      buffer = "t Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\x0d\012  </ImportGroup>\x0d\012  <ImportGr"; if (iIndex == index) return buffer; index++;
      buffer = "oup Label=\"PropertySheets\" Condition=\"'$(Configuration)|$(Platform)'=='Release|Win32'\">\x0d\012    <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists('$(UserRootDir)\\Mic"; if (iIndex == index) return buffer; index++;
      buffer = "rosoft.Cpp.$(Platform).user.props')\" Label=\"LocalAppDataPlatform\" />\x0d\012  </ImportGroup>\x0d\012  <PropertyGroup Label=\"UserMacros\" />\x0d\012  <PropertyGroup />\x0d\012  <ItemDefinitionGroup Condition=\"'$(Configuration)"; if (iIndex == index) return buffer; index++;
      buffer = "|$(Platform)'=='Debug|Win32'\">\x0d\012    <ClCompile>\x0d\012      <PrecompiledHeader>NotUsing</PrecompiledHeader>\x0d\012      <WarningLevel>Level3</WarningLevel>\x0d\012      <Optimization>Disabled</Optimization>\x0d\012      <P"; if (iIndex == index) return buffer; index++;
      buffer = "reprocessorDefinitions>WIN32;_DEBUG;_LIB;_CRT_SECURE_NO_WARNINGS;_SCL_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>\x0d\012      <AdditionalIncludeDirectories>$(PROTOBUF_INCLUDE_DI"; if (iIndex == index) return buffer; index++;
      buffer = "R)</AdditionalIncludeDirectories>\x0d\012      <PrecompiledHeaderFile>\x0d\012      </PrecompiledHeaderFile>\x0d\012      <PrecompiledHeaderOutputFile>\x0d\012      </PrecompiledHeaderOutputFile>\x0d\012    </ClCompile>\x0d\012    <Link"; if (iIndex == index) return buffer; index++;
      buffer = ">\x0d\012      <SubSystem>Windows</SubSystem>\x0d\012      <GenerateDebugInformation>true</GenerateDebugInformation>\x0d\012    </Link>\x0d\012    <Lib>\x0d\012      <AdditionalLibraryDirectories>$(PROTOBUF_LIB_DIR)\\$(Configuratio"; if (iIndex == index) return buffer; index++;
      buffer = "nName)</AdditionalLibraryDirectories>\x0d\012      <AdditionalDependencies>$(PROTOBUF_DEBUG_LIBRARIES)</AdditionalDependencies>\x0d\012    </Lib>\x0d\012  </ItemDefinitionGroup>\x0d\012  <ItemDefinitionGroup Condition=\"'$(Co"; if (iIndex == index) return buffer; index++;
      buffer = "nfiguration)|$(Platform)'=='Release|Win32'\">\x0d\012    <ClCompile>\x0d\012      <WarningLevel>Level3</WarningLevel>\x0d\012      <PrecompiledHeader>NotUsing</PrecompiledHeader>\x0d\012      <Optimization>MaxSpeed</Optimizat"; if (iIndex == index) return buffer; index++;
      buffer = "ion>\x0d\012      <FunctionLevelLinking>true</FunctionLevelLinking>\x0d\012      <IntrinsicFunctions>true</IntrinsicFunctions>\x0d\012      <PreprocessorDefinitions>WIN32;NDEBUG;_LIB;_CRT_SECURE_NO_WARNINGS;_SCL_SECURE"; if (iIndex == index) return buffer; index++;
      buffer = "_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>\x0d\012      <AdditionalIncludeDirectories>$(PROTOBUF_INCLUDE_DIR)</AdditionalIncludeDirectories>\x0d\012      <PrecompiledHeaderFile>\x0d\012      </Pr"; if (iIndex == index) return buffer; index++;
      buffer = "ecompiledHeaderFile>\x0d\012      <PrecompiledHeaderOutputFile>\x0d\012      </PrecompiledHeaderOutputFile>\x0d\012    </ClCompile>\x0d\012    <Link>\x0d\012      <SubSystem>Windows</SubSystem>\x0d\012      <GenerateDebugInformation>tru"; if (iIndex == index) return buffer; index++;
      buffer = "e</GenerateDebugInformation>\x0d\012      <EnableCOMDATFolding>true</EnableCOMDATFolding>\x0d\012      <OptimizeReferences>true</OptimizeReferences>\x0d\012    </Link>\x0d\012    <Lib>\x0d\012      <AdditionalLibraryDirectories>$("; if (iIndex == index) return buffer; index++;
      buffer = "PROTOBUF_LIB_DIR)\\$(ConfigurationName)</AdditionalLibraryDirectories>\x0d\012      <AdditionalDependencies>$(PROTOBUF_RELEASE_LIBRARIES)</AdditionalDependencies>\x0d\012    </Lib>\x0d\012  </ItemDefinitionGroup>\x0d\012  <Im"; if (iIndex == index) return buffer; index++;
      oLength = 128;
      buffer = "port Project=\"$(VCTargetsPath)\\Microsoft.Cpp.targets\" />\x0d\012  <ImportGroup Label=\"ExtensionTargets\">\x0d\012  </ImportGroup>\x0d\012</Project>"; if (iIndex == index) return buffer; index++;
      oLength = 0;
      return NULL;
    }
    virtual const char * getMd5() { return "c86c34b8c888a02b17c55819e4ac8bc9"; }
    virtual char * newBuffer()
    {
      size_t size = getSize();
      char * buffer = new char[size];
      if (buffer == NULL)
        return NULL;
      size_t numSegments = getNumSegments();
      size_t segmentLength = 0;
      size_t index = 0;
      for(size_t i=0; i<numSegments; i++)
      {
        const char * segmentBuffer = getSegment(i, segmentLength);
        memcpy(&buffer[index], segmentBuffer, segmentLength);
        index += segmentLength;
      }
      return buffer;
    }
    virtual bool save(const char * iFilename)
    {
      FILE * f = fopen(iFilename, "wb");
      if (!f) return false;
      size_t numSegments = getNumSegments();
      size_t segmentLength = 0;
      const char * buffer = NULL;
      for(size_t i=0; i<numSegments; i++)
      {
        buffer = getSegment(i, segmentLength);
        fwrite(buffer, 1, segmentLength, f);
      }
      fclose(f);
      return true;
    }
  };
  File & getProtoLibProjectFile() { static ProtoLibProjectFile _instance; return _instance; }
}; //bin2cpp
