/**
 * This file was generated by bin2cpp v2.2.0
 * Copyright (C) 2013-2019 end2endzone.com. All rights reserved.
 * bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp
 * Source code for file 'DCOMPLUGIN_COMPONENT_NAMEServerImpl.vcxproj', last modified 1552228002.
 * Do not modify this file.
 */
#include "EmbeddedFileServerImplProject.h"
#include <stdio.h> //for FILE
#include <string> //for memcpy
namespace bin2cpp
{
  class ServerImplProjectFile : public virtual bin2cpp::File
  {
  public:
    ServerImplProjectFile() { build(); }
    virtual ~ServerImplProjectFile() {}
    virtual size_t getSize() const { return 5052; }
    virtual const char * getFilename() const { return "DCOMPLUGIN_COMPONENT_NAMEServerImpl.vcxproj"; }
    virtual const char * getBuffer() const { return mBuffer.c_str(); }
    void build()
    {
      mBuffer.clear();
      mBuffer.reserve(getSize()); //allocate all required memory at once to prevent reallocations
      mBuffer.append("\357\273\277<\?xml version=\"1.0\" encoding=\"utf-8\"\?>\r\n<Project DefaultTargets=\"Build\" ToolsVersion=\"4.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\r\n  <ItemGroup Label=\"ProjectConfigurations\">\r", 200);
      mBuffer.append("\n    <ProjectConfiguration Include=\"Debug|Win32\">\r\n      <Configuration>Debug</Configuration>\r\n      <Platform>Win32</Platform>\r\n    </ProjectConfiguration>\r\n    <ProjectConfiguration Include=\"Release", 200);
      mBuffer.append("|Win32\">\r\n      <Configuration>Release</Configuration>\r\n      <Platform>Win32</Platform>\r\n    </ProjectConfiguration>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <ClInclude Include=\"DCOMPLUGIN_COMPONENT_NAMES", 200);
      mBuffer.append("erverImpl.h\" />\r\n    <DCOMPLUGIN_ALL_SERVICES_VCXPROJ />\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <ClCompile Include=\"DCOMPLUGIN_COMPONENT_NAMEServerImpl.template.cpp\" />\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n  ", 200);
      mBuffer.append("  <ProjectReference Include=\"DCOMPLUGIN_COMPONENT_NAMEProtoLib.vcxproj\">\r\n      <Project>{DCOMPLUGIN_PROTOLIB_PROJECT_GUID_LOWER}</Project>\r\n    </ProjectReference>\r\n  </ItemGroup>\r\n  <PropertyGroup L", 200);
      mBuffer.append("abel=\"Globals\">\r\n    <ProjectGuid>{DCOMPLUGIN_SERVER_IMPL_PROJECT_GUID_UPPER}</ProjectGuid>\r\n    <Keyword>Win32Proj</Keyword>\r\n    <RootNamespace>DCOMPLUGIN_COMPONENT_NAMEServerImpl</RootNamespace>\r\n ", 200);
      mBuffer.append(" </PropertyGroup>\r\n  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.Default.props\" />\r\n  <PropertyGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Debug|Win32\'\" Label=\"Configuration\">\r\n    <Configur", 200);
      mBuffer.append("ationType>StaticLibrary</ConfigurationType>\r\n    <UseDebugLibraries>true</UseDebugLibraries>\r\n    <CharacterSet>MultiByte</CharacterSet>\r\n  </PropertyGroup>\r\n  <PropertyGroup Condition=\"\'$(Configurati", 200);
      mBuffer.append("on)|$(Platform)\'==\'Release|Win32\'\" Label=\"Configuration\">\r\n    <ConfigurationType>StaticLibrary</ConfigurationType>\r\n    <UseDebugLibraries>false</UseDebugLibraries>\r\n    <WholeProgramOptimization>tru", 200);
      mBuffer.append("e</WholeProgramOptimization>\r\n    <CharacterSet>MultiByte</CharacterSet>\r\n  </PropertyGroup>\r\n  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.props\" />\r\n  <ImportGroup Label=\"ExtensionSettings\">\r\n  ", 200);
      mBuffer.append("</ImportGroup>\r\n  <ImportGroup Label=\"PropertySheets\" Condition=\"\'$(Configuration)|$(Platform)\'==\'Debug|Win32\'\">\r\n    <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"e", 200);
      mBuffer.append("xists(\'$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\')\" Label=\"LocalAppDataPlatform\" />\r\n  </ImportGroup>\r\n  <ImportGroup Label=\"PropertySheets\" Condition=\"\'$(Configuration)|$(Platform)\'==\'Relea", 200);
      mBuffer.append("se|Win32\'\">\r\n    <Import Project=\"$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\" Condition=\"exists(\'$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\')\" Label=\"LocalAppDataPlatform\" />\r\n  </Im", 200);
      mBuffer.append("portGroup>\r\n  <PropertyGroup Label=\"UserMacros\" />\r\n  <PropertyGroup />\r\n  <ItemDefinitionGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Debug|Win32\'\">\r\n    <ClCompile>\r\n      <PrecompiledHeader>No", 200);
      mBuffer.append("tUsing</PrecompiledHeader>\r\n      <WarningLevel>Level3</WarningLevel>\r\n      <Optimization>Disabled</Optimization>\r\n      <PreprocessorDefinitions>WIN32;_DEBUG;_LIB;_CRT_SECURE_NO_WARNINGS;_SCL_SECURE", 200);
      mBuffer.append("_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n      <AdditionalIncludeDirectories>$(PROTOBUF_INCLUDE_DIR)</AdditionalIncludeDirectories>\r\n      <PrecompiledHeaderFile>\r\n      </Pr", 200);
      mBuffer.append("ecompiledHeaderFile>\r\n      <PrecompiledHeaderOutputFile>\r\n      </PrecompiledHeaderOutputFile>\r\n    </ClCompile>\r\n    <Link>\r\n      <SubSystem>Windows</SubSystem>\r\n      <GenerateDebugInformation>tru", 200);
      mBuffer.append("e</GenerateDebugInformation>\r\n    </Link>\r\n    <Lib>\r\n      <AdditionalLibraryDirectories>$(PROTOBUF_LIB_DIR)\\$(ConfigurationName)</AdditionalLibraryDirectories>\r\n      <AdditionalDependencies>$(PROTO", 200);
      mBuffer.append("BUF_DEBUG_LIBRARIES)</AdditionalDependencies>\r\n    </Lib>\r\n  </ItemDefinitionGroup>\r\n  <ItemDefinitionGroup Condition=\"\'$(Configuration)|$(Platform)\'==\'Release|Win32\'\">\r\n    <ClCompile>\r\n      <Warnin", 200);
      mBuffer.append("gLevel>Level3</WarningLevel>\r\n      <PrecompiledHeader>NotUsing</PrecompiledHeader>\r\n      <Optimization>MaxSpeed</Optimization>\r\n      <FunctionLevelLinking>true</FunctionLevelLinking>\r\n      <Intrin", 200);
      mBuffer.append("sicFunctions>true</IntrinsicFunctions>\r\n      <PreprocessorDefinitions>WIN32;NDEBUG;_LIB;_CRT_SECURE_NO_WARNINGS;_SCL_SECURE_NO_WARNINGS;%(PreprocessorDefinitions)</PreprocessorDefinitions>\r\n      <Ad", 200);
      mBuffer.append("ditionalIncludeDirectories>$(PROTOBUF_INCLUDE_DIR)</AdditionalIncludeDirectories>\r\n      <PrecompiledHeaderFile>\r\n      </PrecompiledHeaderFile>\r\n      <PrecompiledHeaderOutputFile>\r\n      </Precompil", 200);
      mBuffer.append("edHeaderOutputFile>\r\n    </ClCompile>\r\n    <Link>\r\n      <SubSystem>Windows</SubSystem>\r\n      <GenerateDebugInformation>true</GenerateDebugInformation>\r\n      <EnableCOMDATFolding>true</EnableCOMDATF", 200);
      mBuffer.append("olding>\r\n      <OptimizeReferences>true</OptimizeReferences>\r\n    </Link>\r\n    <Lib>\r\n      <AdditionalLibraryDirectories>$(PROTOBUF_LIB_DIR)\\$(ConfigurationName)</AdditionalLibraryDirectories>\r\n     ", 200);
      mBuffer.append(" <AdditionalDependencies>$(PROTOBUF_RELEASE_LIBRARIES)</AdditionalDependencies>\r\n    </Lib>\r\n  </ItemDefinitionGroup>\r\n  <Import Project=\"$(VCTargetsPath)\\Microsoft.Cpp.targets\" />\r\n  <ImportGroup Lab", 200);
      mBuffer.append("el=\"ExtensionTargets\">\r\n  </ImportGroup>\r\n</Project>", 52);
    }
    virtual bool save(const char * iFilename) const
    {
      FILE * f = fopen(iFilename, "wb");
      if (!f) return false;
      size_t fileSize = getSize();
      const char * buffer = getBuffer();
      fwrite(buffer, 1, fileSize, f);
      fclose(f);
      return true;
    }
  private:
    std::string mBuffer;
  };
  const File & getServerImplProjectFile() { static ServerImplProjectFile _instance; return _instance; }
}; //bin2cpp
