/**
 * This file was generated by
 * bin2cpp v1.3.
 * Copyright (C) 2013-2014 end2endzone.com. All rights reserved.
 * Do not modify this file.
 */
#include ".\EmbeddedFileProtoLibFilters.h"
#include <stdio.h> //for FILE
#include <string> //for memcpy
namespace bin2cpp
{
  class ProtoLibFiltersFile : public virtual bin2cpp::File
  {
  public:
    ProtoLibFiltersFile() {}
    ~ProtoLibFiltersFile() {}
    virtual size_t getSize() { return 2450; }
    virtual size_t getSegmentSize() { return 200; }
    virtual size_t getNumSegments() { return 13; }
    virtual const char * getFilename() { return "DCOMPLUGIN_COMPONENT_NAMEProtoLib.vcxproj.filters"; }
    virtual const char * getSegment(size_t iIndex, size_t & oLength)
    {
      oLength = 0;
      if (iIndex >= getNumSegments())
        return NULL;
      const char * buffer = NULL;
      size_t index = 0;
      oLength = getSegmentSize();
      buffer = "\xef\xbb\277<?xml version=\"1.0\" encoding=\"utf-8\"?>\x0d\012<Project ToolsVersion=\"4.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\x0d\012  <ItemGroup>\x0d\012    <Filter Include=\"Source Files\">\x0d\012      <UniqueId"; if (iIndex == index) return buffer; index++;
      buffer = "entifier>{4FC737F1-C7A5-4376-A066-2A32D752A2FF}</UniqueIdentifier>\x0d\012      <Extensions>cpp;c;cc;cxx;def;odl;idl;hpj;bat;asm;asmx</Extensions>\x0d\012    </Filter>\x0d\012    <Filter Include=\"Header Files\">\x0d\012      "; if (iIndex == index) return buffer; index++;
      buffer = "<UniqueIdentifier>{93995380-89BD-4b04-88EB-625FBE52EBFB}</UniqueIdentifier>\x0d\012      <Extensions>h;hpp;hxx;hm;inl;inc;xsd</Extensions>\x0d\012    </Filter>\x0d\012    <Filter Include=\"Resource Files\">\x0d\012      <Uniqu"; if (iIndex == index) return buffer; index++;
      buffer = "eIdentifier>{67DA6AB6-F800-4c08-8B7A-83BB121AAD01}</UniqueIdentifier>\x0d\012      <Extensions>rc;ico;cur;bmp;dlg;rc2;rct;bin;rgs;gif;jpg;jpeg;jpe;resx;tiff;tif;png;wav;mfcribbon-ms</Extensions>\x0d\012    </Filt"; if (iIndex == index) return buffer; index++;
      buffer = "er>\x0d\012    <Filter Include=\"Proto Files\">\x0d\012      <UniqueIdentifier>{6340cb88-3eb8-415b-bbb0-95e85db92aa3}</UniqueIdentifier>\x0d\012    </Filter>\x0d\012    <Filter Include=\"Services\">\x0d\012      <UniqueIdentifier>{caa"; if (iIndex == index) return buffer; index++;
      buffer = "91ff0-ee16-4a3d-a372-c7965012e4ab}</UniqueIdentifier>\x0d\012    </Filter>\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <None Include=\"DCOMPLUGIN_PROTO_FILE_NAME.proto\">\x0d\012      <Filter>Proto Files</Filter>\x0d\012    </No"; if (iIndex == index) return buffer; index++;
      buffer = "ne>\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <ClCompile Include=\"dcomplugin.pb.cc\">\x0d\012      <Filter>Proto Files</Filter>\x0d\012    </ClCompile>\x0d\012    <ClCompile Include=\"DCOMPLUGIN_PROTO_FILE_NAME.pb.cc\">\x0d\012      "; if (iIndex == index) return buffer; index++;
      buffer = "<Filter>Proto Files</Filter>\x0d\012    </ClCompile>\x0d\012    <ClCompile Include=\"MessageSerializer.cpp\">\x0d\012      <Filter>Source Files</Filter>\x0d\012    </ClCompile>\x0d\012    <ClCompile Include=\"ErrorHandlers.cpp\">\x0d\012   "; if (iIndex == index) return buffer; index++;
      buffer = "   <Filter>Source Files</Filter>\x0d\012    </ClCompile>\x0d\012    <ClCompile Include=\"Registry.cpp\">\x0d\012      <Filter>Source Files</Filter>\x0d\012    </ClCompile>\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <ClInclude Include"; if (iIndex == index) return buffer; index++;
      buffer = "=\"dcomplugin.pb.h\">\x0d\012      <Filter>Proto Files</Filter>\x0d\012    </ClInclude>\x0d\012    <ClInclude Include=\"DCOMPLUGIN_PROTO_FILE_NAME.pb.h\">\x0d\012      <Filter>Proto Files</Filter>\x0d\012    </ClInclude>\x0d\012    <ClInclu"; if (iIndex == index) return buffer; index++;
      buffer = "de Include=\"MessageSerializer.h\">\x0d\012      <Filter>Header Files</Filter>\x0d\012    </ClInclude>\x0d\012    <ClInclude Include=\"ErrorHandlers.h\">\x0d\012      <Filter>Header Files</Filter>\x0d\012    </ClInclude>\x0d\012    <ClInclu"; if (iIndex == index) return buffer; index++;
      buffer = "de Include=\"IComErrorProvider.h\">\x0d\012      <Filter>Header Files</Filter>\x0d\012    </ClInclude>\x0d\012    <ClInclude Include=\"Registry.h\">\x0d\012      <Filter>Header Files</Filter>\x0d\012    </ClInclude>\x0d\012    <DCOMPLUGIN_A"; if (iIndex == index) return buffer; index++;
      oLength = 50;
      buffer = "LL_SERVICES_FILTERS />\x0d\012  </ItemGroup>\x0d\012</Project>"; if (iIndex == index) return buffer; index++;
      oLength = 0;
      return NULL;
    }
    virtual const char * getMd5() { return "9283ddc39c55dac8f0b929d381ee6801"; }
    virtual char * newBuffer()
    {
      size_t size = getSize();
      char * buffer = new char[size];
      if (buffer == NULL)
        return NULL;
      size_t numSegments = getNumSegments();
      size_t segmentLength = 0;
      size_t index = 0;
      for(size_t i=0; i<numSegments; i++)
      {
        const char * segmentBuffer = getSegment(i, segmentLength);
        memcpy(&buffer[index], segmentBuffer, segmentLength);
        index += segmentLength;
      }
      return buffer;
    }
    virtual bool save(const char * iFilename)
    {
      FILE * f = fopen(iFilename, "wb");
      if (!f) return false;
      size_t numSegments = getNumSegments();
      size_t segmentLength = 0;
      const char * buffer = NULL;
      for(size_t i=0; i<numSegments; i++)
      {
        buffer = getSegment(i, segmentLength);
        fwrite(buffer, 1, segmentLength, f);
      }
      fclose(f);
      return true;
    }
  };
  File & getProtoLibFiltersFile() { static ProtoLibFiltersFile _instance; return _instance; }
}; //bin2cpp
