/**
 * This file was generated by bin2cpp v2.2.0
 * Copyright (C) 2013-2019 end2endzone.com. All rights reserved.
 * bin2cpp is open source software, see http://github.com/end2endzone/bin2cpp
 * Source code for file 'DCOMPLUGIN_COMPONENT_NAMEClient.vcxproj.filters', last modified 1552228002.
 * Do not modify this file.
 */
#include "EmbeddedFileClientFilters.h"
#include <stdio.h> //for FILE
#include <string> //for memcpy
namespace bin2cpp
{
  class ClientFiltersFile : public virtual bin2cpp::File
  {
  public:
    ClientFiltersFile() { build(); }
    virtual ~ClientFiltersFile() {}
    virtual size_t getSize() const { return 1074; }
    virtual const char * getFilename() const { return "DCOMPLUGIN_COMPONENT_NAMEClient.vcxproj.filters"; }
    virtual const char * getBuffer() const { return mBuffer.c_str(); }
    void build()
    {
      mBuffer.clear();
      mBuffer.reserve(getSize()); //allocate all required memory at once to prevent reallocations
      mBuffer.append("\357\273\277<\?xml version=\"1.0\" encoding=\"utf-8\"\?>\r\n<Project ToolsVersion=\"4.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\r\n  <ItemGroup>\r\n    <Filter Include=\"Source Files\">\r\n      <UniqueId", 200);
      mBuffer.append("entifier>{9a84c84f-eb91-4e49-94a6-6d232a4b41ce}</UniqueIdentifier>\r\n      <Extensions>cpp;c;cxx;rc;def;r;odl;idl;hpj;bat</Extensions>\r\n    </Filter>\r\n    <Filter Include=\"Header Files\">\r\n      <Unique", 200);
      mBuffer.append("Identifier>{a21d2163-701e-4f9e-8df3-a858975b9c99}</UniqueIdentifier>\r\n      <Extensions>h;hpp;hxx;hm;inl</Extensions>\r\n    </Filter>\r\n    <Filter Include=\"Resource Files\">\r\n      <UniqueIdentifier>{9d", 200);
      mBuffer.append("0d71fc-5afa-4013-995d-277f13cfcd3c}</UniqueIdentifier>\r\n      <Extensions>ico;cur;bmp;dlg;rc2;rct;bin;rgs;gif;jpg;jpeg;jpe</Extensions>\r\n    </Filter>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <ClInclude In", 200);
      mBuffer.append("clude=\"DCOMPLUGIN_COMPONENT_NAMEClient.h\">\r\n      <Filter>Header Files</Filter>\r\n    </ClInclude>\r\n  </ItemGroup>\r\n  <ItemGroup>\r\n    <ClCompile Include=\"DCOMPLUGIN_COMPONENT_NAMEClient.cpp\">\r\n      <", 200);
      mBuffer.append("Filter>Source Files</Filter>\r\n    </ClCompile>\r\n  </ItemGroup>\r\n</Project>", 74);
    }
    virtual bool save(const char * iFilename) const
    {
      FILE * f = fopen(iFilename, "wb");
      if (!f) return false;
      size_t fileSize = getSize();
      const char * buffer = getBuffer();
      fwrite(buffer, 1, fileSize, f);
      fclose(f);
      return true;
    }
  private:
    std::string mBuffer;
  };
  const File & getClientFiltersFile() { static ClientFiltersFile _instance; return _instance; }
}; //bin2cpp
