/**
 * This file was generated by
 * bin2cpp v1.3.
 * Copyright (C) 2013-2014 end2endzone.com. All rights reserved.
 * Do not modify this file.
 */
#include ".\EmbeddedFileErrorHandlersHeader.h"
#include <stdio.h> //for FILE
#include <string> //for memcpy
namespace bin2cpp
{
  class ErrorHandlersHeaderFile : public virtual bin2cpp::File
  {
  public:
    ErrorHandlersHeaderFile() {}
    ~ErrorHandlersHeaderFile() {}
    virtual size_t getSize() { return 1082; }
    virtual size_t getSegmentSize() { return 200; }
    virtual size_t getNumSegments() { return 6; }
    virtual const char * getFilename() { return "ErrorHandlers.h"; }
    virtual const char * getSegment(size_t iIndex, size_t & oLength)
    {
      oLength = 0;
      if (iIndex >= getNumSegments())
        return NULL;
      const char * buffer = NULL;
      size_t index = 0;
      oLength = getSegmentSize();
      buffer = "#pragma once\x0d\x0a\x0d\012#define WIN32_LEAN_AND_MEAN    // Exclude rarely-used stuff from Windows headers\x0d\012#include <windows.h>\x0d\x0a\x0d\012#include <string>\x0d\x0a\x0d\012namespace DCOMPLUGIN_PACKAGE_NAME {\x0d\x0a\x0d\012///<summary>Provid"; if (iIndex == index) return buffer; index++;
      buffer = "e the file name of the current executable.</summary>\x0d\012///<returns>Returns a string containing the file name of the current executable. ie: MyProcessName.exe</returns>\x0d\012std::string getProcessFilename()"; if (iIndex == index) return buffer; index++;
      buffer = ";\x0d\x0a\x0d\012///<summary>Display an error message box which shows the last error code and its description.</summary>\x0d\012void MessageBoxLastError();\x0d\x0a\x0d\012///<summary>Display an error message box which shows the la"; if (iIndex == index) return buffer; index++;
      buffer = "st error code and its description.</summary>\x0d\012///<param name=\"hr\">A return value of a call to a Win32 API.</param>\x0d\012void MessageBoxLastComError(HRESULT hr);\x0d\x0a\x0d\012///<summary>Returns a string representat"; if (iIndex == index) return buffer; index++;
      buffer = "ion of the given error code.</summary>\x0d\012///<param name=\"hr\">A return value of a call to a Win32 API.</param>\x0d\012///<returns>Returns a string representation of the given error code.</returns>\x0d\012std::strin"; if (iIndex == index) return buffer; index++;
      oLength = 82;
      buffer = "g GetComErrorDescription(HRESULT hr);\x0d\x0a\x0d\012}  // namespace DCOMPLUGIN_PACKAGE_NAME\x0d\x0a"; if (iIndex == index) return buffer; index++;
      oLength = 0;
      return NULL;
    }
    virtual const char * getMd5() { return "569630f039049cb93db9486bab78e7b2"; }
    virtual char * newBuffer()
    {
      size_t size = getSize();
      char * buffer = new char[size];
      if (buffer == NULL)
        return NULL;
      size_t numSegments = getNumSegments();
      size_t segmentLength = 0;
      size_t index = 0;
      for(size_t i=0; i<numSegments; i++)
      {
        const char * segmentBuffer = getSegment(i, segmentLength);
        memcpy(&buffer[index], segmentBuffer, segmentLength);
        index += segmentLength;
      }
      return buffer;
    }
    virtual bool save(const char * iFilename)
    {
      FILE * f = fopen(iFilename, "wb");
      if (!f) return false;
      size_t numSegments = getNumSegments();
      size_t segmentLength = 0;
      const char * buffer = NULL;
      for(size_t i=0; i<numSegments; i++)
      {
        buffer = getSegment(i, segmentLength);
        fwrite(buffer, 1, segmentLength, f);
      }
      fclose(f);
      return true;
    }
  };
  File & getErrorHandlersHeaderFile() { static ErrorHandlersHeaderFile _instance; return _instance; }
}; //bin2cpp
