/**
 * This file was generated by
 * bin2cpp v1.3.
 * Copyright (C) 2013-2014 end2endzone.com. All rights reserved.
 * Do not modify this file.
 */
#include ".\EmbeddedFileClientFilters.h"
#include <stdio.h> //for FILE
#include <string> //for memcpy
namespace bin2cpp
{
  class ClientFiltersFile : public virtual bin2cpp::File
  {
  public:
    ClientFiltersFile() {}
    ~ClientFiltersFile() {}
    virtual size_t getSize() { return 1074; }
    virtual size_t getSegmentSize() { return 200; }
    virtual size_t getNumSegments() { return 6; }
    virtual const char * getFilename() { return "DCOMPLUGIN_COMPONENT_NAMEClient.vcxproj.filters"; }
    virtual const char * getSegment(size_t iIndex, size_t & oLength)
    {
      oLength = 0;
      if (iIndex >= getNumSegments())
        return NULL;
      const char * buffer = NULL;
      size_t index = 0;
      oLength = getSegmentSize();
      buffer = "\xef\xbb\277<?xml version=\"1.0\" encoding=\"utf-8\"?>\x0d\012<Project ToolsVersion=\"4.0\" xmlns=\"http://schemas.microsoft.com/developer/msbuild/2003\">\x0d\012  <ItemGroup>\x0d\012    <Filter Include=\"Source Files\">\x0d\012      <UniqueId"; if (iIndex == index) return buffer; index++;
      buffer = "entifier>{9a84c84f-eb91-4e49-94a6-6d232a4b41ce}</UniqueIdentifier>\x0d\012      <Extensions>cpp;c;cxx;rc;def;r;odl;idl;hpj;bat</Extensions>\x0d\012    </Filter>\x0d\012    <Filter Include=\"Header Files\">\x0d\012      <Unique"; if (iIndex == index) return buffer; index++;
      buffer = "Identifier>{a21d2163-701e-4f9e-8df3-a858975b9c99}</UniqueIdentifier>\x0d\012      <Extensions>h;hpp;hxx;hm;inl</Extensions>\x0d\012    </Filter>\x0d\012    <Filter Include=\"Resource Files\">\x0d\012      <UniqueIdentifier>{9d"; if (iIndex == index) return buffer; index++;
      buffer = "0d71fc-5afa-4013-995d-277f13cfcd3c}</UniqueIdentifier>\x0d\012      <Extensions>ico;cur;bmp;dlg;rc2;rct;bin;rgs;gif;jpg;jpeg;jpe</Extensions>\x0d\012    </Filter>\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <ClInclude In"; if (iIndex == index) return buffer; index++;
      buffer = "clude=\"DCOMPLUGIN_COMPONENT_NAMEClient.h\">\x0d\012      <Filter>Header Files</Filter>\x0d\012    </ClInclude>\x0d\012  </ItemGroup>\x0d\012  <ItemGroup>\x0d\012    <ClCompile Include=\"DCOMPLUGIN_COMPONENT_NAMEClient.cpp\">\x0d\012      <"; if (iIndex == index) return buffer; index++;
      oLength = 74;
      buffer = "Filter>Source Files</Filter>\x0d\012    </ClCompile>\x0d\012  </ItemGroup>\x0d\012</Project>"; if (iIndex == index) return buffer; index++;
      oLength = 0;
      return NULL;
    }
    virtual const char * getMd5() { return "0285c1c8c9037a90957443d359d17083"; }
    virtual char * newBuffer()
    {
      size_t size = getSize();
      char * buffer = new char[size];
      if (buffer == NULL)
        return NULL;
      size_t numSegments = getNumSegments();
      size_t segmentLength = 0;
      size_t index = 0;
      for(size_t i=0; i<numSegments; i++)
      {
        const char * segmentBuffer = getSegment(i, segmentLength);
        memcpy(&buffer[index], segmentBuffer, segmentLength);
        index += segmentLength;
      }
      return buffer;
    }
    virtual bool save(const char * iFilename)
    {
      FILE * f = fopen(iFilename, "wb");
      if (!f) return false;
      size_t numSegments = getNumSegments();
      size_t segmentLength = 0;
      const char * buffer = NULL;
      for(size_t i=0; i<numSegments; i++)
      {
        buffer = getSegment(i, segmentLength);
        fwrite(buffer, 1, segmentLength, f);
      }
      fclose(f);
      return true;
    }
  };
  File & getClientFiltersFile() { static ClientFiltersFile _instance; return _instance; }
}; //bin2cpp
